apiVersion: v1
kind: Namespace
metadata:
  name:  costmanagement-metrics-operator

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: costmanagement-metrics-operator
  namespace: costmanagement-metrics-operator
spec:
  targetNamespaces:
  - costmanagement-metrics-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: costmanagement-metrics-operator
  namespace: costmanagement-metrics-operator
spec:
  channel: stable
  name: costmanagement-metrics-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  startingCSV: costmanagement-metrics-operator.2.0.0
  installPlanApproval: Automatic