apiVersion: v1
kind: Namespace
metadata:
  name:  costmanagement-metrics-operator

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: costmanagement-metrics-operator
  namespace: costmanagement-metrics-operator
spec:
  targetNamespaces:
  - costmanagement-metrics-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: costmanagement-metrics-operator
  namespace: costmanagement-metrics-operator
spec:
  channel: stable
  name: costmanagement-metrics-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  startingCSV: costmanagement-metrics-operator.2.0.0
  installPlanApproval: Automatic

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: costmanagement-metrics-operator.2.0.0
  namespace: costmanagement-metrics-operator
rules:
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - costmanagement-metrics-operator.2.0.0
  resources:
  - operatorconditions
  verbs:
  - get
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: costmanagement-metrics-operator.2.0.0
  namespace: costmanagement-metrics-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: costmanagement-metrics-operator.2.0.0
subjects:
- kind: ServiceAccount
  name: costmanagement-metrics-controller-manager
- kind: ServiceAccount
  name: costmanagement-metrics-controller-manager